config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  devise_scope :user do
    post 'set_email', to: 'oauth_callbacks#set_email'
  end
  root to: 'questions#index'

  concern :voteable do
    member do
      post :vote_for
      post :vote_against
      delete :delete_vote
    end
  end

  concern :commentable do
    resources :comments, shallow: true
  end

  resources :questions, concerns: %i[voteable commentable] do
    resources :answers, concerns: %i[voteable commentable], shallow: true, only: %i[new create destroy update] do
      post :mark_best, on: :member
    end
    resources :subscriptions, shallow: true, only: %i[create destroy]
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create update destroy], shallow: true
      end
    end
  end

  resources :files, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: :index

  get 'search', to: 'search#search'

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Commentable

  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_many :votes, dependent: :destroy, as: :voteable
  belongs_to :author, class_name: 'User'
  has_one :reward, dependent: :destroy
  has_many :subscriptions, dependent: :destroy

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank
  accepts_nested_attributes_for :reward, reject_if: :all_blank

  validates :title, :body, presence: true

  after_create :calculate_reputation
  after_create :create_subscription

  def subscribed?(user)
    subscriptions.exists?(user: user)
  end

  def subscription(user)
    subscriptions.find_by(user_id: user.id)
  end

  private

  def calculate_reputation
    ReputationJob.perform_later(self)
  end

  def create_subscription
    subscriptions.create(user: author, question: self)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :question, only: %i[show update destroy]

  authorize_resource

  def index
    @questions = Question.all
    render json: @questions, each_serializer: QuestionsSerializer
  end

  def show
    render json: @question
  end

  def create
    @question = current_resource_owner.questions.new(question_params)
    @question.save ? head(:ok) : head(422)
  end

  def update
    @question.update(question_params) ? head(:ok) : head(422)
  end

  def destroy
    @question.destroy ? head(:ok) : head(422)
  end

  private

  def question_params
    params.require(:question).permit(:title, :body,
                                     links_attributes: %i[name url])
  end

  def question
    @question = Question.with_attached_files.find(params[:id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_question, only: %i[show new update destroy]
  after_action :publish_question, only: [:create]

  authorize_resource

  include Voted

  def index
    @questions = Question.all
  end

  def show
    @answer = Answer.new
    @answer.links.new
  end

  def new
    @question.links.build
    @question.reward = Reward.new
  end

  def create
    @question = Question.new(question_params)
    @question.author = current_user

    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    @question.update(question_params)
    @questions = Question.all
  end

  def destroy
    if @question.destroy
      redirect_to questions_path, notice: 'Your question successfully deleted.'
    else
      render questions_path
    end
  end

  private

  def set_question
    @question ||= params[:id] ? Question.with_attached_files.find(params[:id]) : Question.new
    gon.question_id = @question.id
    gon.user_id = current_user.id if current_user
  end

  def question_params
    params.require(:question).permit(:title, :body, files: [],
                                                    links_attributes: %i[name url],
                                                    reward_attributes: %i[name image])
  end

  def publish_question
    return if @question.errors.any?

    renderer = ApplicationController.renderer_with_signed_in_user(current_user)
    ActionCable.server.broadcast(
      'questions',
      renderer.render(
        partial: 'questions/question',
        locals: { question: @question, current_user: nil }
      )
    )
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_question.html.slim
- cache ['index', question] do
  p
    = link_to question.title, question_path(question), method: :get
    = question.body
    = render 'subscriptions/subscriptions', question: question
    - if can?(:destroy, question)
      = link_to 'Delete', question, method: :delete
      = link_to 'Edit', '#', class: 'edit-question-link', data: { question_id: question.id }
    = render 'shared/votes', resource: question
  = form_with model: question, class: 'hidden', html: { id: "edit-question-#{question.id}" } do |f|
    = f.label :title, 'Question title'
    = f.text_field :title
    = f.label :body, 'Question body'
    = f.text_area :body
    = f.label :files
    = f.file_field :files, multiple: true
    = render 'links/form', form: f, link_new: Link.new
    = f.submit 'Save'

app/views/questions/index.html.slim
= render 'search/form'
.search_results_block
.questions
  = render @questions
p= link_to 'Ask question', new_question_path if can?(:create, Question)
.question-errors
  = render 'shared/errors', resource: @question
p= link_to 'My rewards', rewards_path if can?(:index, Reward)

app/views/questions/new.html.slim
= render 'shared/errors', resource: @question
= form_with model: @question do |f|
  = f.label :title
  = f.text_field :title
  = f.label :body
  = f.text_area :body
  = f.label :files
  = f.file_field :files, multiple: true
  = render 'links/form', form: f, link_new: nil
  = render 'rewards/form', form: f
  = f.submit 'Ask'

app/views/questions/show.html.slim
- cache @question do
  h1= @question.title
  p= @question.body
  .question-files
    = render 'shared/files', resource: @question
  .question-links
    = render 'shared/links', resource: @question
  .question-comments
    p Comments:
    = render @question.comments
  - if can?(:create, Comment)
    = render 'comments/form', resource: @question
  .reward
      = render @question.reward if @question.reward.present?
  - if can?(:create, Answer)
    .answer-errors
      = render 'shared/errors', resource: @answer
    = form_with model: [@question, @answer], class: 'new_answer' do |form|
      = form.label :body
      = form.text_area :body
      = form.label :files
      = form.file_field :files, multiple: true
      = render 'links/form', form: form, link_new: nil
      = form.submit 'Answer'
  .answers
    = render @question.answers

app/views/questions/update.js.erb
$('.question-errors').html("<%= render 'shared/errors', resource: @question %>");

<% unless @question.errors.present? %>
  $('.questions').html('<%= j render @questions %>');
<% end %>