config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  devise_scope :user do
    post 'set_email', to: 'oauth_callbacks#set_email'
  end
  root to: 'questions#index'

  concern :voteable do
    member do
      post :vote_for
      post :vote_against
      delete :delete_vote
    end
  end

  concern :commentable do
    resources :comments, shallow: true
  end

  resources :questions, concerns: %i[voteable commentable] do
    resources :answers, concerns: %i[voteable commentable], shallow: true, only: %i[new create destroy update] do
      post :mark_best, on: :member
    end
    resources :subscriptions, shallow: true, only: %i[create destroy]
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create update destroy], shallow: true
      end
    end
  end

  resources :files, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: :index

  get 'search', to: 'search#search'

  mount ActionCable.server => '/cable'
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  protect_from_forgery except: :search
  skip_authorization_check

  def search
    @search_results = SphinxSearch.search_results(params[:search_text], params[:search_object]) if params[:search_text] && params[:search_object]
  end
end

app/views/search/_form.html.slim
= form_tag search_path, method: :get, remote: true do
  = text_field_tag :search_text, params[:search_text]
  = select_tag :search_object, options_for_select(SphinxSearch::SEARCH_OBJECTS, params[:search_object])
  = submit_tag 'Search'

app/views/search/_search_result.html.slim
.search_results_block
  h3 Search results:
  - unless results.empty?
    - results.each do |result|
      - if result.is_a?(Question)
        p= link_to(result.title, question_path(result))
      - elsif result.is_a?(Answer)
        p= link_to(result.body, question_path(result.question))
      - elsif result.is_a?(Comment)
        - question = result.commentable.is_a?(Answer) ? result.commentable.question : result.commentable
        p= link_to(result.body, question_path(question))
      - else
        p= result.email

app/views/search/search.js.erb
$(".search_results_block").replaceWith('<%= j render 'search_result', results: @search_results %>');