config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  devise_scope :user do
    post 'set_email', to: 'oauth_callbacks#set_email'
  end
  root to: 'questions#index'

  concern :voteable do
    member do
      post :vote_for
      post :vote_against
      delete :delete_vote
    end
  end

  concern :commentable do
    resources :comments, shallow: true
  end

  resources :questions, concerns: %i[voteable commentable] do
    resources :answers, concerns: %i[voteable commentable], shallow: true, only: %i[new create destroy update] do
      post :mark_best, on: :member
    end
    resources :subscriptions, shallow: true, only: %i[create destroy]
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create update destroy], shallow: true
      end
    end
  end

  resources :files, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: :index

  get 'search', to: 'search#search'

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Commentable

  has_many :links, dependent: :destroy, as: :linkable
  has_many :votes, dependent: :destroy, as: :voteable
  belongs_to :question, touch: true
  belongs_to :author, class_name: 'User'
  has_one :reward, dependent: :nullify

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank

  validates :body, presence: true

  after_create :send_notification

  scope :best, -> { order best: :desc }

  def mark_best
    question.answers.update_all(best: false)
    update(best: true)
    self.reward = question.reward if question.reward.present?
  end

  private

  def send_notification
    NewAnswersNotificationJob.perform_later(question.author, self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question, only: %i[new create destroy]
  before_action :set_answer, only: %i[destroy update mark_best]
  before_action :set_answer_question, only: %i[destroy update mark_best]
  after_action :publish_answer, only: [:create]

  authorize_resource

  include Voted

  def new; end

  def create
    @answer = @question.answers.create(answer_params.merge(author: current_user))
  end

  def destroy
    @answer.destroy
    @answers = @question.answers
  end

  def update
    @answer.update(answer_params)
  end

  def mark_best
    @answer.mark_best
  end

  private

  def answer_params
    params.require(:answer).permit(:body, :author, files: [], links_attributes: %i[name url])
  end

  def set_question
    @question ||= params[:question_id] ? Question.with_attached_files.find(params[:question_id]) : Question.new
  end

  def set_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def set_answer_question
    @question = @answer.question
  end

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast(
      "answer_question_#{@question.id}",
      answer: @answer,
      links: @answer.links,
      user_id: current_user.id
    )
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :question, only: %i[index create]
  before_action :answers, only: :index
  before_action :answer, only: %i[show update destroy]
  authorize_resource

  def index
    render json: @answers, each_serializer: AnswersSerializer
  end

  def show
    render json: @answer
  end

  def create
    @answer = @question.answers.new(answer_params.merge(author: current_resource_owner))
    @answer.save ? head(:ok) : head(422)
  end

  def update
    @answer.update(answer_params) ? head(:ok) : head(422)
  end

  def destroy
    @answer.destroy ? head(:ok) : head(422)
  end

  private

  def question
    @question = Question.with_attached_files.find(params[:question_id])
  end

  def answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body,
                                   links_attributes: %i[name url])
  end

  def answers
    @answers ||= @question.answers
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- cache answer do
  - if answer.best
    p This is best answer
    .reward
      = render answer.reward if answer.reward.present?
  p id = "answer-#{answer.id}"
    .answer-files
      = render 'shared/files', resource: answer
    = answer.body
    .answer-links
      = render 'shared/links', resource: answer
    div class="answer-#{answer.id}-comments"
      = render answer.comments
    - if can?(:create, Comment)
      = render 'comments/form', resource: answer
    - if can?(:update, answer)
      = link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }
      = link_to 'Delete', answer_path(answer), method: :delete, remote: true
      = link_to 'Best answer', mark_best_answer_path(answer), method: :post, remote: true if can?(:mark_best, answer)
    = render 'shared/votes', resource: answer
  = form_with model: answer, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
    = f.label :body, 'Your answer'
    = f.text_area :body
    = f.label :files
    = f.file_field :files, multiple: true
    = render 'links/form', form: f, link_new: Link.new
    = f.submit 'Save'

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.persisted? %>
$('.answers').append('<%= j render @answer %>');
$('.new-answer #answer_body').val('');
window.GistEmbed.init()
<% end %>

app/views/answers/destroy.js.erb
$('.answers').html('<%= j render @answers %>');

app/views/answers/mark_best.js.erb
$('.answers').html('<%= j render @question.answers.best %>');

app/views/answers/update.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% unless @answer.errors.present? %>
  $('.answers').html('<%= j render @question.answers %>');
  window.GistEmbed.init()
<% end %>