config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  devise_scope :user do
    post 'set_email', to: 'oauth_callbacks#set_email'
  end
  root to: 'questions#index'

  concern :voteable do
    member do
      post :vote_for
      post :vote_against
      delete :delete_vote
    end
  end

  concern :commentable do
    resources :comments, shallow: true
  end

  resources :questions, concerns: %i[voteable commentable] do
    resources :answers, concerns: %i[voteable commentable], shallow: true, only: %i[new create destroy update] do
      post :mark_best, on: :member
    end
    resources :subscriptions, shallow: true, only: %i[create destroy]
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create update destroy], shallow: true
      end
    end
  end

  resources :files, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: :index

  get 'search', to: 'search#search'

  mount ActionCable.server => '/cable'
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :question
  belongs_to :user
  validates :user_id, uniqueness: { scope: :question_id }
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!
  before_action :question, only: :create
  before_action :subscription, only: :destroy

  authorize_resource

  def create
    @question.subscriptions.create(user: current_user)
  end

  def destroy
    @question = @subscription.question
    subscription.destroy
  end

  private

  def question
    @question = Question.find(params[:question_id])
  end

  def subscription
    @subscription = Subscription.find(params[:id])
  end
end

app/views/subscriptions/_subscriptions.html.slim
div id = "question-#{question.id}-subscribe-button"
  -if current_user
    -if question.subscribed?(current_user)
      = button_to 'Disable notifications', subscription_path(question.subscription(current_user)), remote: true, method: :delete
    -else
      = button_to "Subscribe for new answers notifications", question_subscriptions_path(question), remote: true

app/views/subscriptions/create.js.erb
$("#question-" + <%=@question.id%> + "-subscribe-button").replaceWith('<%= j render 'subscriptions', question: @question %>');

app/views/subscriptions/destroy.js.erb
$("#question-" + <%=@question.id%> + "-subscribe-button").replaceWith('<%= j render 'subscriptions', question: @question %>');